version: "1"
rules:
  - base: bazzite-main
    upstream: ublue-os:main
    mergeMethod: hardreset
    mergeUnstable: false
  - base: main
    upstream: bazzite-main
    mergeMethod: rebase
    mergeUnstable: false
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
